# Generated by Django 4.2.5 on 2023-10-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_booking_no_of_guests_alter_menu_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Booking Records'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menu Item'},
        ),
    ]
